---
# Update the /etc/hosts file
- name: Update the /etc/hosts file
  ansible.builtin.include_tasks: update_hosts.yml
  when: lb_type == 'apache'

# Config Apache Load Balancer
- name: Config Apache Load Balancer
  ansible.builtin.include_tasks: configure_lb.yml
  when: lb_type == 'apache'

# Config Apache Load Balancer SSL certificate
- name: Config Apache Load Balancer SSL certificate
  ansible.builtin.include_tasks: ssl_lb.yml
  when: lb_type == 'apache'
