---
- name: Restart Apache
  become: true
  ansible.builtin.systemd:
    name: httpd
    state: restarted
    enabled: true

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
