---
# Install Nginx
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  when:
    - nginx_lb_enabled
    - load_balancer_is_required

# Deploy load balancer config
- name: Deploy Nginx load balancer configuration
  become: true
  ansible.builtin.template:
    src: load_balancer.conf.j2
    dest: /etc/nginx/conf.d/load_balancer.conf
    mode: '0644'
  notify: Reload Nginx
  when:
    - nginx_lb_enabled
    - load_balancer_is_required

# Remove default Nginx conf
- name: Remove default Nginx site configuration
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx

# Test the new configuration
- name: Test Nginx configuration
  become: true
  ansible.builtin.command: nginx -t
  register: nginx_test
  changed_when: false

# Start and enable Nginx if enabled
- name: Ensure Nginx is started and enabled if load balancing is enabled
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  when:
    - nginx_lb_enabled
    - load_balancer_is_required
