---
- name: Debug lb_type for load balancer hosts
  ansible.builtin.debug:
    msg: "lb_type is {{ lb_type }}"

# Update the /etc/hosts file
- name: Update the /etc/hosts file
  ansible.builtin.include_tasks: update_hosts.yml
  when: lb_type == 'nginx'

# Config Nginx Load Balancer
- name: Config Nginx Load Balancer
  ansible.builtin.include_tasks: configure_lb.yml
  when: lb_type == 'nginx'
