---
# Ensure snapd is installed and active
- name: Ensure snapd is installed and active
  become: true
  ansible.builtin.apt:
    name: snapd
    state: present
    update_cache: true

# Ensure snapd is running and enabled
- name: Ensure snapd service is running
  become: true
  ansible.builtin.systemd:
    name: snapd
    state: started
    enabled: true

# Install Certbot via snap
- name: Install Certbot via snap
  become: true
  community.general.snap:
    name: certbot
    classic: true
    state: present
  register: certbot_install

# Create symlink for Certbot
- name: Create symlink for certbot
  become: true
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
    force: true
