[nfs-server]
172.31.11.175 ansible_ssh_user=ec2-user

[web-servers]
172.31.13.144 ansible_ssh_user=ec2-user
172.31.10.244 ansible_ssh_user=ec2-user
172.31.10.220 ansible_ssh_user=ec2-user

[db-server]
172.31.11.187 ansible_ssh_user=ec2-user

[lb-server]
172.31.9.89 ansible_ssh_user=ubuntu

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'