---
# create the backup marker
- name: Check if backup marker exists in /var/log
  become: true
  ansible.builtin.stat:
    path: /var/log/backup_done_marker
  register: backup_marker

# Install the LVM2 package
- name: Install LVM2 package
  ansible.builtin.package:
    name: lvm2
    state: present

# Ensure necessary directories exist before any operations
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /db
    - /home/recovery/logs

# Partition EBS volumes with parted
- name: Partition EBS volumes with parted
  community.general.parted:
    device: "{{ item }}"
    number: 1
    state: present
    part_type: primary
    fs_type: ext4
    align: optimal
  loop:
    - /dev/xvdb
    - /dev/xvdc
    - /dev/xvdd
  register: parted_results

# Create physical volumes on new partitions
- name: Create physical volumes on new partitions
  ansible.builtin.command: "pvcreate {{ item }}"
  loop:
    - /dev/xvdb1
    - /dev/xvdc1
    - /dev/xvdd1
  args:
    creates: "{{ item }}"

# Create volume group 'dbdata-vg'
- name: Create volume group 'dbdata-vg'
  community.general.lvg:
    vg: dbdata-vg
    pvs:
      - /dev/xvdb1
      - /dev/xvdc1
      - /dev/xvdd1

- name: Pause for 5 seconds to allow VG recognition
  ansible.builtin.pause:
    seconds: 5

# Get the total size of volume group 'dbdata-vg' in gigabytes
- name: Get total size of volume group dbdata-vg
  ansible.builtin.command: "vgs --noheadings --units g --nosuffix -o vg_size dbdata-vg"
  register: vg_size_cmd
  changed_when: false

- name: Set VG total size fact
  ansible.builtin.set_fact:
    vg_total_size: "{{ vg_size_cmd.stdout | trim | float }}"

- name: Debug VG total size
  ansible.builtin.debug:
    msg: "Volume group total size: {{ vg_total_size }}G"

# Calculate half the VG total size for the logical volumes
- name: Set half VG size for logical volumes
  ansible.builtin.set_fact:
    half_vg_size: "{{ (vg_total_size | float / 2) | round(0, 'floor') }}"

- name: Debug half VG size
  ansible.builtin.debug:
    msg: "Half of VG size: {{ half_vg_size }}G"

# Create logical volumes for database data and logs using dynamically calculated size
- name: Create logical volumes for database data and logs using dynamically calculated size
  community.general.lvol:
    vg: dbdata-vg
    lv: "{{ item }}"
    size: "{{ half_vg_size }}g"
    state: present
  loop:
    - db-lv
    - log-lv

# Create ext4 filesystem on the new logical volumes
- name: Create ext4 filesystem on the new logical volumes
  community.general.filesystem:
    fstype: ext4
    dev: "/dev/dbdata-vg/{{ item }}"
  loop:
    - db-lv
    - log-lv

# Backup /var/log only if it is not mounted yet (i.e. this is the first run)
- name: Backup /var/log to /home/recovery/logs using synchronize
  become: true
  ansible.posix.synchronize:
    src: /var/log/
    dest: /home/recovery/logs/
    archive: yes
  when: not backup_marker.stat.exists

# Mount the logical volume for database and log data persistently to /db and /var/log respectively
- name: Mount logical volumes persistently
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    opts: defaults
    state: mounted
  loop:
    - { path: "/db", src: "/dev/dbdata-vg/db-lv" }
    - { path: "/var/log", src: "/dev/dbdata-vg/log-lv" }

# Restore /var/log from backup, but only if the backup task actually ran
- name: Restore /var/log from backup using synchronize
  become: true
  ansible.posix.synchronize:
    src: /home/recovery/logs/
    dest: /var/log/
    archive: yes
  when: not backup_marker.stat.exists

# create a marker file to indicate that the backup/restore process has completed
- name: Create marker file to indicate backup/restore completed
  become: true
  ansible.builtin.file:
    path: /var/log/backup_done_marker
    state: touch
