---
- name: Install Apache (httpd)
  become: true
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Install git and nano
  become: true
  ansible.builtin.dnf:
    name: 
      - git
      - nano
    state: present

- name: Install NFS client utilities (nfs-utils and nfs4-acl-tools)
  become: true
  ansible.builtin.dnf:
    name:
      - nfs-utils
      - nfs4-acl-tools
    state: present

- name: Install official MySQL client
  become: true
  ansible.builtin.dnf:
    name: mysql
    state: present
