---
- name: Install apache (httpd), git, nano, nfs-utils, nfs4-acl-tools, and mariadb
  become: true
  ansible.builtin.dnf:
    name:
      - httpd
      - git
      - nano
      - nfs-utils
      - nfs4-acl-tools
      - mariadb
    state: present
