---
- name: Install repositories and switch PHP module stream
  become: true
  when: ([ php_version ] | select('defined') | list | length) == 1
  block:

    - name: Import EPEL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ webserver_epel_gpg_key_url }}"

    - name: Install EPEL package
      ansible.builtin.dnf:
        name: "{{ webserver_epel_package_url }}"
        state: present
      notify: Update package cache
    
    - name: Install Remi GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ webserver_remi_gpg_key_url }}"
    
    - name: Install Remi package
      ansible.builtin.dnf:
        name: "{{ webserver_remi_package_url }}"
        state: present
      notify: Update package cache

    - name: Switch to PHP module stream from Remi
      ansible.builtin.dnf:
        module_enable:
          - "php:remi-{{ php_version }}"
        state: present
