---
- name: Install repositories and switch PHP module stream
  become: true
  when: ([ epel_repo_url, epel_gpg_key_url, remi_repo_url, remi_gpg_key_url, php_version ] | select('defined') | list | length) == 3
  block:
    - name: Import EPEL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ epel_gpg_key_url }}"

    - name: Install EPEL repository
      ansible.builtin.dnf:
        name: "{{ epel_repo_url }}"
        state: present

    - name: Import Remi GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ remi_gpg_key_url }}"

    - name: Install Remi repository
      ansible.builtin.dnf:
        name: "{{ remi_repo_url }}"
        state: present

    - name: Switch to PHP module stream from Remi
      ansible.builtin.dnf:
        module_enable:
          - "php:remi-{{ php_version }}"
        state: present
