---
# Include repository and module stream configuration tasks
- name: Include EPEL and Remi repository tasks
  ansible.builtin.include_tasks: epel_remi.yml

# Include PHP installation tasks
- name: Include PHP installation tasks
  ansible.builtin.include_tasks: php.yml

# Include Apache, git, NFS utilities, and MySQL client installation tasks
- name: Include Apache, git, NFS, and MySQL client installation tasks
  ansible.builtin.include_tasks: apache_git_nfs_mysql.yml

# Include SELinux configuration tasks (if applicable)
- name: Include SELinux configuration tasks for Apache and PHP
  ansible.builtin.include_tasks: selinux.yml

# Include repository cloning and HTML management tasks
- name: Include repository cloning and HTML management tasks
  ansible.builtin.include_tasks: repo_clone.yml
