---
- name: Install Apache (httpd)
  become: true
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Install PHP
  become: true
  ansible.builtin.dnf:
    name: php
    state: present

- name: Install git
  become: true
  ansible.builtin.dnf:
    name: git
    state: present

# New task: Install MySQL client
- name: Install MySQL client
  become: true
  ansible.builtin.dnf:
    name: mariadb  # or mysql if you prefer the official package
    state: present

- name: Clone the repository
  become: true
  ansible.builtin.git:
    repo: "{{ tooling_repo }}"
    dest: /var/www/html/
    force: true
    version: main

- name: Copy HTML content to one level up
  become: true
  ansible.builtin.copy:
    src: /var/www/html/html/
    dest: /var/www/html/
    remote_src: true
    mode: "0755"

- name: Remove redundant nested html directory
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent

- name: Restart and enable Apache
  become: true
  ansible.builtin.systemd:
    name: httpd
    state: restarted
    enabled: true
