---
- name: Ensure local mount point exists for web content
  become: true
  ansible.builtin.file:
    path: /var/www
    state: directory
    owner: nobody
    group: nobody
    mode: '0777'
    recurse: true

- name: Mount NFS share for web content persistently
  become: true
  ansible.posix.mount:
    path: /var/www
    src: "{{ nfs_server_ip }}:/mnt/apps"
    fstype: nfs
    opts: "rw,nosuid"
    state: mounted
    dump: 0
    passno: 0
