- name: Update web, NFS, and DB servers
  hosts: nfs_server, web_servers, db_server
  become: true
  tasks:
    - name: Ensure Wireshark is installed
      ansible.builtin.yum:
        name: wiresharkclea
        state: present

- name: Update LB server
  hosts: lb_server
  become: true
  tasks:
    - name: Update apt repo
      ansible.builtin.apt:
        update_cache: true

    - name: Ensure Wireshark is installed
      ansible.builtin.apt:
        name: wireshark
        state: present
