---
- name: Load dynamic variables
  hosts: all
  become: true
  tasks:
    - name: Include environment variables from dynamic assignments
      ansible.builtin.include_tasks: "../dynamics-assignments/env-vars.yml"
  tags:
    - always

# Set up MySQL on database servers
- name: Set up MySQL
  hosts: uat_db
  become: true
  roles:
    - dbserver

# Set up MySQL on database servers
- name: Set up NFS server
  hosts: uat_nfs
  become: true
  roles:
    - nfs-server

# Set up Apache and PHP on web servers
- name: Import UAT webservers play
  ansible.builtin.import_playbook: "../static-assignments/uat-webserver.yml"
