---
- name: Load dynamic variables
  hosts: all
  become: true
  tasks:
    - name: Include environment variables from dynamic assignments
      ansible.builtin.include_tasks: "../dynamics-assignments/env-vars.yml"
  tags:
    - always

# Set up MySQL on database servers
- name: Set up MySQL
  hosts: db_server
  become: true
  roles:
    - dbserver

# Set up NFS server
- name: Set up NFS server
  hosts: nfs_server
  become: true
  roles:
    - nfs-server

# Set up Apache and PHP on web servers
- name:  Set up Apache and PHP on web servers
  ansible.builtin.import_playbook: "../static-assignments/uat-webserver.yml"

# Configure load balancers
- name: Configure load balancer
  hosts: lb_servers
  roles:
    - { role: cleanup_lb }
    - { role: nginx_lb, when: load_balancer_is_required and nginx_lb_enabled }
    - { role: apache_lb, when: load_balancer_is_required and apache_lb_enabled }
