---
# Install the LVM2, git nano package
- name: Install LVM2, git, nano package
  ansible.builtin.package:
    name:
      - lvm2
      - git
      - nano
    state: present

# Ensure necessary directories exist before any operations
- name: Ensure required directories exist with correct ownership and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nobody
    mode: '0777'
    recurse: true
  loop:
    - /mnt/apps
    - /mnt/logs
    - /mnt/opt

# Partition EBS volumes with parted
- name: Partition EBS volumes with parted
  community.general.parted:
    device: "{{ item }}"
    number: 1
    state: present
    part_type: primary
    fs_type: ext4
    align: optimal
  loop:
    - /dev/xvdb
    - /dev/xvdc
    - /dev/xvdd
  register: parted_results

# Create physical volumes on new partitions
- name: Create physical volumes on new partitions
  ansible.builtin.command: "pvcreate {{ item }}"
  loop:
    - /dev/xvdb1
    - /dev/xvdc1
    - /dev/xvdd1
  args:
    creates: "{{ item }}"

# Create volume group 'webdata-vg'
- name: Create volume group 'webdata-vg'
  community.general.lvg:
    vg: webdata-vg
    pvs:
      - /dev/xvdb1
      - /dev/xvdc1
      - /dev/xvdd1

- name: Pause for 5 seconds to allow VG recognition
  ansible.builtin.pause:
    seconds: 5

# Get the total size of volume group 'webdata-vg' in gigabytes
- name: Get total size of volume group webdata-vg
  ansible.builtin.command: "vgs --noheadings --units g --nosuffix -o vg_size webdata-vg"
  register: vg_size_cmd
  changed_when: false

- name: Set VG total size fact
  ansible.builtin.set_fact:
    vg_total_size: "{{ vg_size_cmd.stdout | trim | float }}"

- name: Debug VG total size
  ansible.builtin.debug:
    msg: "Volume group total size: {{ vg_total_size }}G"

# Calculate half the VG total size for the logical volumes
- name: Set one-third VG size for logical volumes
  ansible.builtin.set_fact:
    one_third_vg_size: "{{ (vg_total_size | float / 3) | round(0, 'floor') }}"

- name: Debug one-third VG size
  ansible.builtin.debug:
    msg: "one-third of VG size: {{ one_third_vg_size }}G"

# Create logical volumes for database data and logs using dynamically calculated size
- name: Create logical volumes for database data and logs using dynamically calculated size
  community.general.lvol:
    vg: webdata-vg
    lv: "{{ item }}"
    size: "{{ one_third_vg_size }}g"
    state: present
  loop:
    - apps-lv
    - logs-lv
    - opt-lv

# Create ext4 filesystem on the new logical volumes
- name: Create ext4 filesystem on the new logical volumes
  community.general.filesystem:
    fstype: xfs
    dev: "/dev/webdata-vg/{{ item }}"
  loop:
    - apps-lv
    - logs-lv
    - opt-lv

# Mount the logical volume to the specified directories
- name: Mount logical volumes persistently
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    opts: defaults
    state: mounted
  loop:
    - { path: "/mnt/apps", src: "/dev/webdata-vg/apps-lv" }
    - { path: "/mnt/log", src: "/dev/webdata-vg/logs-lv" }
    - { path: "/mnt/opt", src: "/dev/webdata-vg/opt-lv" }
