---
- name: Clone the tooling repository using environment variable
  become: true
  ansible.builtin.git:
    repo: "{{ tooling_repo }}"
    dest: /tmp/tooling
    version: main
    force: true

- name: Copy html directory from cloned repository to /mnt/apps
  become: true
  ansible.builtin.copy:
    src: /tmp/tooling/html/
    dest: /mnt/apps/html/
    remote_src: true
    mode: "0755"

- name: Remove cloned tooling repository from /tmp
  become: true
  ansible.builtin.file:
    path: /tmp/tooling
    state: absent
